'use strict';

const fs = require('fs');
const path = require('path');

// Canonical part naming.
//
// The number in an OOXML part name (slide7.xml, image240.png, theme4.xml) is
// not part of the document; it is whatever counter the writer happened to be
// on. PowerPoint does not keep the numbers it is handed: on every save it walks
// the package from the root and renames every numbered part to a dense 1..N
// sequence in the order it visits them. So a deck written by anything other
// than PowerPoint - split out of a bigger deck, generated by a script, produced
// by python-pptx - has every part renamed the first time a human saves it. In a
// tracked directory that reads as "every file deleted, a differently named copy
// added", which buries the one slide that actually changed.
//
// Giving the parts that same canonical numbering up front removes the churn: a
// PowerPoint-written deck is already canonical, so this is a no-op for it, and
// any other deck is brought to the form PowerPoint would have converged to
// anyway. Only the numbers move - content, relationship ids and element order
// are untouched.
//
// The whole rename is planned and checked before anything is written: every
// relationship target has to resolve to a part that exists and every part has
// to keep a content type, or the package is left exactly as it was.

const ROOT_RELS = '_rels/.rels';

function isRelsPath(rel) {
  return rel === ROOT_RELS || rel.includes('/_rels/');
}

function relsPathFor(partRel) {
  const dir = path.posix.dirname(partRel);
  const base = path.posix.basename(partRel);
  return (dir === '.' ? '' : dir + '/') + '_rels/' + base + '.rels';
}

// The part a .rels file belongs to. _rels/.rels belongs to the package itself.
function ownerOfRels(relsRel) {
  if (relsRel === ROOT_RELS) return null;
  const dir = path.posix.dirname(path.posix.dirname(relsRel));
  const base = path.posix.basename(relsRel).replace(/\.rels$/, '');
  return (dir === '.' ? '' : dir + '/') + base;
}

// Resolve a relationship Target against the directory of the part that owns it.
function resolveTarget(ownerDir, target) {
  if (target.startsWith('/')) return target.slice(1);
  return path.posix.normalize((ownerDir ? ownerDir + '/' : '') + target);
}

function parseRels(xml) {
  const out = [];
  for (const tag of xml.match(/<Relationship\b[^>]*?\/>/g) || []) {
    const id = (tag.match(/\bId="([^"]*)"/) || [])[1];
    const target = (tag.match(/\bTarget="([^"]*)"/) || [])[1];
    const mode = (tag.match(/\bTargetMode="([^"]*)"/) || [])[1];
    if (id === undefined || target === undefined) continue;
    out.push({ id, target, external: mode === 'External', tag });
  }
  return out;
}

function ridNumber(id) {
  const m = /(\d+)$/.exec(id);
  return m ? +m[1] : Number.MAX_SAFE_INTEGER;
}

// Part families whose trailing number is an identity, not a counter, so it must
// be left alone. ppt/comments holds modernComment_<slide>_<comment>.xml and
// modernComment_<slide>_<hash>.xml; PowerPoint keeps those names as they are.
const KEEP_NAMES_IN = ['ppt/comments'];

// PowerPoint counts most families from 1 (slide1.xml, image1.png) but leaves the
// first embedded workbook unnumbered: Microsoft_Excel_Worksheet.xlsx, then
// Microsoft_Excel_Worksheet1.xlsx. Families like that also let an unnumbered
// name take part in the counter, which is otherwise a sign the part is not
// counted at all (presentation.xml, viewProps.xml).
const ELIDE_FIRST_NUMBER_IN = ['ppt/embeddings'];

// slide7.xml -> {prefix: 'slide', ext: '.xml'}; presentation.xml -> null.
// The counter has to sit directly behind a letter: modernComment_105_0.xml and
// modernComment_E56_C0AEDC67.xml carry an id, not a counter.
function splitNumbered(base, elideFirst) {
  const m = /^(.*[A-Za-z])(\d+)(\.[^.]*)$/.exec(base);
  if (m) return { prefix: m[1], ext: m[3] };
  if (!elideFirst) return null;
  const u = /^(.*[A-Za-z])(\.[^.]*)$/.exec(base);
  return u ? { prefix: u[1], ext: u[2] } : null;
}

function listParts(dir) {
  const out = [];
  (function walk(d, rel) {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const name = rel ? rel + '/' + entry.name : entry.name;
      if (entry.isDirectory()) walk(path.join(d, entry.name), name);
      else out.push(name);
    }
  })(dir, '');
  return out.sort();
}

function dirOf(rel) {
  const d = path.posix.dirname(rel);
  return d === '.' ? '' : d;
}

// Walk the package from the root, visiting each part's relationships in rId
// order, and hand every numbered part the next number for its directory and
// name prefix. Extensions share a prefix's counter, which is what PowerPoint
// does: image240.jpg, image241.png, image242.svg become image1.jpg, image2.png,
// image3.svg.
function planRenames(pptxDir, relsOf) {
  const counters = new Map();
  const rename = new Map(); // old part path -> new part path
  const visited = new Set();

  const assign = (partRel) => {
    const dir = dirOf(partRel);
    if (KEEP_NAMES_IN.includes(dir)) return;
    const elideFirst = ELIDE_FIRST_NUMBER_IN.includes(dir);
    const split = splitNumbered(path.posix.basename(partRel), elideFirst);
    if (!split) return; // unnumbered parts (presentation.xml, viewProps.xml, ...)
    const key = dir + ' ' + split.prefix;
    const n = (counters.get(key) || 0) + 1;
    counters.set(key, n);
    const suffix = elideFirst ? (n === 1 ? '' : String(n - 1)) : String(n);
    const next = (dir ? dir + '/' : '') + split.prefix + suffix + split.ext;
    if (next !== partRel) rename.set(partRel, next);
  };

  const walk = (relsRel, ownerDir) => {
    const rels = relsOf.get(relsRel);
    if (!rels) return;
    for (const r of rels.slice().sort((a, b) => ridNumber(a.id) - ridNumber(b.id))) {
      if (r.external) continue;
      const target = resolveTarget(ownerDir, r.target);
      if (visited.has(target)) continue;
      visited.add(target);
      assign(target);
      walk(relsPathFor(target), dirOf(target));
    }
  };

  walk(ROOT_RELS, '');
  return rename;
}

function replaceTargetBase(tag, newBase) {
  return tag.replace(/\bTarget="([^"]*)"/, (whole, target) => {
    const dir = target.slice(0, target.length - path.posix.basename(target).length);
    return 'Target="' + dir + newBase + '"';
  });
}

// Plans the rename, checks the result, and only then moves files and writes the
// rewritten .rels / [Content_Types].xml. Returns the number of parts renamed,
// 0 when the package was already canonical, or -1 when it was left untouched
// because the planned result did not validate.
function normalizePartNames(pptxDir) {
  const parts = listParts(pptxDir);

  const relsOf = new Map();
  for (const rel of parts) {
    if (isRelsPath(rel)) relsOf.set(rel, parseRels(fs.readFileSync(path.join(pptxDir, rel), 'utf8')));
  }
  if (!relsOf.has(ROOT_RELS)) return 0;

  const rename = planRenames(pptxDir, relsOf);
  if (rename.size === 0) return 0;

  const bail = (why) => {
    console.warn('warning: skipped part-name normalization (' + why + ')');
    return -1;
  };

  // Where every file ends up, .rels files following the part they describe.
  const moveTo = new Map();
  for (const rel of parts) {
    if (isRelsPath(rel)) {
      const owner = ownerOfRels(rel);
      const mapped = owner && rename.get(owner);
      if (mapped) moveTo.set(rel, relsPathFor(mapped));
    } else if (rename.has(rel)) {
      moveTo.set(rel, rename.get(rel));
    }
  }
  const after = parts.map((rel) => moveTo.get(rel) || rel);
  if (new Set(after).size !== after.length) return bail('two parts would end up with the same name');

  // Rewrite the relationship targets and the content-type overrides on the
  // planned names, then check the result before touching the working copy.
  const before = new Set(parts);
  const present = new Set(after);
  const rewritten = new Map();
  for (const [relsRel, rels] of relsOf) {
    const ownerDir = relsRel === ROOT_RELS ? '' : dirOf(ownerOfRels(relsRel));
    let xml = fs.readFileSync(path.join(pptxDir, relsRel), 'utf8');
    for (const r of rels) {
      if (r.external) continue;
      const resolved = resolveTarget(ownerDir, r.target);
      const mapped = rename.get(resolved) || resolved;
      // A relationship that already dangled in the deck we were handed stays as
      // it is; one that resolved has to keep resolving.
      if (before.has(resolved) && !present.has(mapped)) {
        return bail('relationship ' + r.id + ' in ' + relsRel + ' would point at missing ' + mapped);
      }
      if (mapped !== resolved) xml = xml.replace(r.tag, replaceTargetBase(r.tag, path.posix.basename(mapped)));
    }
    rewritten.set(moveTo.get(relsRel) || relsRel, xml);
  }

  const ctRel = '[Content_Types].xml';
  if (!parts.includes(ctRel)) return bail('missing [Content_Types].xml');
  let ct = fs.readFileSync(path.join(pptxDir, ctRel), 'utf8');
  const overridesBefore = new Set(
    (ct.match(/<Override\b[^>]*?\/>/g) || [])
      .map((t) => (t.match(/\bPartName="([^"]*)"/) || [])[1])
      .filter(Boolean)
      .map((p) => p.replace(/^\//, ''))
  );
  const overrides = new Set();
  for (const tag of ct.match(/<Override\b[^>]*?\/>/g) || []) {
    const partName = (tag.match(/\bPartName="([^"]*)"/) || [])[1];
    if (!partName) continue;
    const old = partName.replace(/^\//, '');
    const mapped = rename.get(old) || old;
    overrides.add(mapped);
    if (mapped !== old) ct = ct.replace(tag, tag.replace(/\bPartName="[^"]*"/, 'PartName="/' + mapped + '"'));
  }
  const defaults = new Set(
    (ct.match(/<Default\b[^>]*?\/>/g) || [])
      .map((t) => (t.match(/\bExtension="([^"]*)"/) || [])[1])
      .filter(Boolean)
      .map((e) => e.toLowerCase())
  );
  // Only the renaming is ours to get right: a part that had a content type has
  // to still have one afterwards. Decks that already carry parts no content type
  // covers - PowerPoint leaves [trash]/0000.dat behind, for one - are left as
  // they are rather than treated as a failure.
  const covered = (rel, over) => over.has(rel)
    || defaults.has(path.posix.extname(rel).replace(/^\./, '').toLowerCase());
  for (const [oldRel, newRel] of rename) {
    if (covered(oldRel, overridesBefore) && !covered(newRel, overrides)) {
      return bail('part ' + oldRel + ' would lose its content type as ' + newRel);
    }
  }

  // The plan holds. Move through staging names so a part can take a name
  // another part is giving up, then write the rewritten XML.
  const staged = [];
  let i = 0;
  for (const [from, to] of moveTo) {
    if (from === to) continue;
    const tmp = dirOf(from) + '/__gpptx' + (i++) + path.posix.extname(from);
    fs.renameSync(path.join(pptxDir, from), path.join(pptxDir, tmp));
    staged.push([tmp, to]);
  }
  for (const [tmp, to] of staged) {
    const dst = path.join(pptxDir, to);
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.renameSync(path.join(pptxDir, tmp), dst);
  }
  for (const [rel, xml] of rewritten) fs.writeFileSync(path.join(pptxDir, rel), xml);
  fs.writeFileSync(path.join(pptxDir, ctRel), ct);

  return rename.size;
}

module.exports = { normalizePartNames };
